// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFVnFxg8VAbfOCInET24fLhuGCIQTFFyY',
    appId: '1:104319031456:web:27681f43bdadd507f851c5',
    messagingSenderId: '104319031456',
    projectId: 'niftyniota',
    authDomain: 'niftyniota.firebaseapp.com',
    storageBucket: 'niftyniota.appspot.com',
    measurementId: 'G-3NEGFGM39H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiueUM63heaWyatCNprbv5urPizszpNaE',
    appId: '1:104319031456:android:ff0a839559e17186f851c5',
    messagingSenderId: '104319031456',
    projectId: 'niftyniota',
    storageBucket: 'niftyniota.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEhfFT9C-U8LNr0d9h_gG1YI2L9xcqWuw',
    appId: '1:104319031456:ios:bbd67b54159a2231f851c5',
    messagingSenderId: '104319031456',
    projectId: 'niftyniota',
    storageBucket: 'niftyniota.appspot.com',
    androidClientId: '104319031456-8i81ao1cj579ri1qajun7gpj4bsi4sg6.apps.googleusercontent.com',
    iosClientId: '104319031456-2j6r63eb8rlc3n8n5g7c1mm3dk9g97g0.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEhfFT9C-U8LNr0d9h_gG1YI2L9xcqWuw',
    appId: '1:104319031456:ios:bbd67b54159a2231f851c5',
    messagingSenderId: '104319031456',
    projectId: 'niftyniota',
    storageBucket: 'niftyniota.appspot.com',
    androidClientId: '104319031456-8i81ao1cj579ri1qajun7gpj4bsi4sg6.apps.googleusercontent.com',
    iosClientId: '104319031456-2j6r63eb8rlc3n8n5g7c1mm3dk9g97g0.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFVnFxg8VAbfOCInET24fLhuGCIQTFFyY',
    appId: '1:104319031456:web:d5b1dc7e29ddfc53f851c5',
    messagingSenderId: '104319031456',
    projectId: 'niftyniota',
    authDomain: 'niftyniota.firebaseapp.com',
    storageBucket: 'niftyniota.appspot.com',
    measurementId: 'G-8MNG3NVDJ1',
  );

}